# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool: 
  name: mpool
  demands: Agent.Version -equals 4.248.0


resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: vilasagentpool
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: './pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
